### ISSUE TITLE
Confusing README header

### ISSUE THREAD

**Issue by nihiluis** [rustcc/coroutine-rs#74]
[dependencies.coroutine]
git = "0.5.0"

what does this mean in the header?

If I put it in Cargo.toml "0.5.0" is an invalid url.

**Comment by zonyitoo** [comment]
Sorry for that. You should use

```toml
[dependencies]
coroutine = "0.5.0"
```
