### ISSUE TITLE
Unable to compile program: no `FnBox` in `boxed`

### ISSUE THREAD

**Issue by mjarkk** [rustcc/coroutine-rs#77]
When i try to compile my program that includes this library i get the following error:  
![image](https://user-images.githubusercontent.com/15320763/80375632-e9f86c80-8898-11ea-8781-05ed0cee7c5d.png)

Dependencies in `Cargo.toml`  
```toml
[dependencies]
reqwest = { version = "0.10", features = ["blocking", "json"] }
tokio = { version = "0.2", features = ["full"] }
serde = {version = "1.0.106", features = ["derive"]}
rustc-serialize = "0.3.24"
coroutine = "0.8"
```

`rustup show`:
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/mark/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.44.0-nightly (b2e36e6c2 2020-04-22)
```

Code used for testing:
```rust
fn main() {
  Coroutine::spawn(|me,_| {
    loop {
      thread::sleep(Duration::from_secs(1));
      println!("Hello 2");
    }
  });
  loop {
      thread::sleep(Duration::from_secs(1));
      println!("Hello 1");
  }
}
```

I'm very new to rust and i'm not yet sure how everything works so please be nice 🥺
